### ISSUE TITLE
color/com_facebook_button_background_color_focused_disabled) not found.

### ISSUE THREAD

**Issue by Gursewak-Uppal** [romatroskin/social_share_plugin#12]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/apple/.gradle/caches/transforms-2/files-2.1/c8d5e31b5f497089d6092f8f1989c851/jetified-facebook-share-4.42.0/res/drawable/com_facebook_button_send_background.xml:27: AAPT: error: resource color/com_facebook_button_background_color_focused_disabled (aka pixz.io.pixz:color/com_facebook_button_background_color_focused_disabled) not found.

     /Users/apple/.gradle/caches/transforms-2/files-2.1/c8d5e31b5f497089d6092f8f1989c851/jetified-facebook-share-4.42.0/res/drawable/com_facebook_button_send_background.xml:40: AAPT: error: resource color/com_facebook_button_background_color_focused (aka pixz.io.pixz:color/com_facebook_button_background_color_focused) not found.

     /Users/apple/.gradle/caches/transforms-2/files-2.1/c8d5e31b5f497089d6092f8f1989c851/jetified-facebook-share-4.42.0/res/drawable/com_facebook_button_send_background.xml:41: AAPT: error: resource color/com_facebook_button_border_color_focused (aka pixz.io.pixz:color/com_facebook_button_border_color_focused) not found.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get 
    more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

     BUILD FAILED in 19s

**Comment by romatroskin** [comment]
try with updated version please

**Comment by kaarens93** [comment]
I got this error too and resolved by adding 
`implementation 'com.facebook.android:facebook-android-sdk:[5,6)'`
to dependencies in android/app/build.gradle
