### ISSUE TITLE
Share to instagram feed/story not working

### ISSUE THREAD

**Issue by kaarens93** [romatroskin/social_share_plugin#15]
When I try to share via instagram, bottom opens with 'Share to: Direct, Feed, Stories' but none of these options work. When I click 'Direct', I get a list of my contacts but I am unable to send anything because instagram crashes when I try. When I click 'Feed', it says 'unable to load image'. When I click 'Stories', the screen turns white and then goes back to my original screen

Here is my code: 
`  launchApp() async {
    await SocialSharePlugin.shareToFeedInstagram("image/*", 'images/planet_earth.png');
  }`

**Comment by romatroskin** [comment]
wrong usage, plugin needs a full path to the image, not a short from assets, look at the example
