### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020

### ISSUE THREAD

**Issue by ben060788** [romatroskin/social_share_plugin#16]
Hi, @romatroskin 
I submit my app to app store, and recive the following infomation

`
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020.
`
`
see https://developer.apple.com/documentation/uikit/uiwebview for more information.
`

therefore, i remove the social_share_plugin and submit again.
the warning doesn't appear.

is there any solution?

**Comment by romatroskin** [comment]
it's a question to the flutter team

**Comment by awhitford** [comment]
If your code isn't using `UIWebView`, then it must be coming from a dependency.  I doubt Flutter is using `UIWebView`; my bet is that it is coming from the **Facebook SDK** and **Twitter SDK**.  For Facebook, it looks like an upgrade may solve the issue.  For Twitter, the SDK is no longer supported, so there is no upgrade.

**Comment by ben060788** [comment]
@awhitford 
I try to upgrade Facebook SDK version and it would be not useful.
and then i remove Twitter SDK because i never use it.
Finally, the issue `ITMS-90809`  disappears.
Thanks for your help.

**Comment by romatroskin** [comment]
Removed Twitter SDK, replaced by Intent for android and openURL for iOS :) Thanks for reports!!
