### ISSUE TITLE
Podspec pegs FBSDK dependency to 5.8.0

### ISSUE THREAD

**Issue by awhitford** [romatroskin/social_share_plugin#17]
Podspec pegs the FBSDK to 5.8.0:
```
  s.dependency 'FBSDKCoreKit', '5.8.0'
  s.dependency 'FBSDKShareKit', '5.8.0'
```

This caused my app to downgrade from 5.15.1; I am also using [`flutter_facebook_login`](https://github.com/roughike/flutter_facebook_login/blob/master/ios/flutter_facebook_login.podspec) which specifies:
```
  s.dependency 'FBSDKCoreKit', '~> 5.5'
  s.dependency 'FBSDKLoginKit', '~> 5.5'
```

May I suggest tweaking the dependency to be like:
```
  s.dependency 'FBSDKCoreKit', '~> 5.8'
  s.dependency 'FBSDKShareKit', '~> 5.8'
```
Then, we can get upgrades too.  See the [Cocoa Pods Specification](https://guides.cocoapods.org/syntax/podspec.html#dependency) for more information.

**Comment by awhitford** [comment]
I would also double check the [Android side](https://github.com/romatroskin/social_share_plugin/blob/master/android/build.gradle), because this looks artificially constrained too:
```
        implementation 'com.facebook.android:facebook-share:[4,5)'
```

Does version 5.x not work?

I see PR #7 tries to update this, but was never merged.

**Comment by awhitford** [comment]
I'm pretty sure that this version issue is breaking my build.  😭 
```  /Users/anthony/github/acme/project/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m:225:61: error: no visible @interface for 'FBSDKAccessToken' declares the selector
    'initWithTokenString:permissions:declinedPermissions:expiredPermissions:appID:userID:expirationDate:refreshDate:dataAccessExpirationDate:graphDomain:'
            FBSDKAccessToken *token = [[FBSDKAccessToken alloc] initWithTokenString:tokenString
                                       ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by awhitford** [comment]
Confirmed...  My suggestion above resolved the build issue.

**Comment by awhitford** [comment]
Why was this issue closed without an update to the [podspec](https://github.com/romatroskin/social_share_plugin/blob/master/ios/social_share_plugin.podspec)? 😕

**Comment by thongdn-it** [comment]
@awhitford you can try add code in Podfile, remove Podfile.lock and build again.

pod 'FBSDKCoreKit', '5.8.0'
pod 'FBSDKLoginKit', '5.8.0'
pod 'FBSDKShareKit', '5.8.0'

<img width="396" alt="Screenshot 2020-03-26 at 8 11 54 PM" src="https://user-images.githubusercontent.com/44582170/77650468-1ec58b00-6f9e-11ea-9573-2f8f2e0fbdce.png">
