### ISSUE TITLE
Latest Instagram Version Sharing Image to Instagram Feed Doesn't Work

### ISSUE THREAD

**Issue by erdoganabaci** [romatroskin/social_share_plugin#18]
**Describe the bug**
In the **latest version** of instagram (133.0.0.32.120 ) it only creates problems when feeding pictures
Instagram story and video feature works well but **just sharing image to instagram feed doesn't work.**
However every feature works well **in the previous version of Instagram (132.0.0.26.134 )**

**Expected behavior**
Image file is expected to shared to feed via instagram latest version

**Screenshots**
![Screenshot_1584893077](https://user-images.githubusercontent.com/43154455/77254199-b2cae600-6c70-11ea-8853-6817614ddcca.png)

![Screenshot_1584892335](https://user-images.githubusercontent.com/43154455/77253885-962dae80-6c6e-11ea-81d4-6a6b1dc1ea6e.png)

**Smartphone (please complete the following information):**
 - Device: Android Api 28
 - Instagram Version [133.0.0.32.120]

**Additional context**
Please help how to solve instagram to feed image in the instagram latest version(133.0.0.32.120).

**Comment by romatroskin** [comment]
unfortunately it can be broken by the instagram if only feeds is not working, as I can see there was some issues with the stories as well, take a look at https://developers.facebook.com/support/bugs/1258133677908854/
and you can report them as well too, thanks for noticing!

**Comment by erdoganabaci** [comment]
This bugs only all flutter packages sharing to feed instagram images didnt work.I tried also video it works both story and feed but images couldnt work good.Only share image instagram feed didnt work.I think widgets didnt compatable with latest version.Can you fixed this problem ? I tried other flutter widgets same issue.But when I tried to native android share feature works good.Also ios part works good.Only problem is sharing image to feed latest instagram in android.

**Comment by NALAndrod2** [comment]
I got the same problem :(

**Comment by romatroskin** [comment]
https://developers.facebook.com/support/bugs/1326888287510350/

**Comment by romatroskin** [comment]
and it works already on beta of instagram, so as I told, it's not an flutter or mine issue :)

**Comment by aytunch** [comment]
Hi @romatroskin 
Latest [Facebook developer documents](https://developers.facebook.com/docs/instagram/sharing-to-stories) says it is allowed to share videos to Instagram stories
could we implement this for iOS to this cool library?
