### ISSUE TITLE
getting error(I am not be able to install the application)

### ISSUE THREAD

**Issue by prabhunath111** [romatroskin/social_share_plugin#19]
I am using this inside application in manifest...

<meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>

        <meta-data android:name="com.facebook.sdk.ApplicationName"
            android:value="@string/app_name"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />

        <provider android:authorities="com.facebook.app.FacebookContentProvider655962691638709"
            android:name="com.facebook.FacebookContentProvider"
            android:exported="true"/>

        <provider android:name="androidx.core.content.FileProvider"
            android:authorities="com.prabhuindiaexample.corona.social.share.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

and this is my string.xml

<?xml version="1.0" encoding="utf-8"?>

<resources>
<string name="app_name">Corona Clock</string>

/*

*/
<string name="facebook_app_id">655962691638709</string>
</resources>

here is the error what I am getting

Launching lib/main.dart on Redmi Note 7S in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/aponiar-17/Desktop/flutter_project/carona-app-flutter/android/app/src/main/AndroidManifest.xml:58:13-60:57: AAPT: error: resource xml/provider_paths (aka com.prabhuindiaexample.corona:xml/provider_paths) not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin assets_audio_player...
Running Gradle task 'assembleAarRelease'...
Finished with error: ProcessException: Permission denied
  Command: /home/aponiar-17/Desktop/flutter_linux_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/android/gradlew -I=/home/aponiar-17/Desktop/flutter_linux_v1.12.13+hotfix.5-stable/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/home/aponiar-17/Desktop/flutter_linux_v1.12.13+hotfix.5-stable/flutter -Poutput-dir=/home/aponiar-17/Desktop/flutter_project/carona-app-flutter/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

**Comment by prabhunath111** [comment]
i did some mistakes in manifest now fixed

**Comment by vivaan-m** [comment]
What was the mistake i am facing same issue

**Comment by srinivasii** [comment]
@prabhunath111  @vivaan-m hi i am facing the same issue. how you fixed that one

**Comment by prabhunath111** [comment]
Actually I forgot what issue I was faced at that time. Can you please send
me the exact issue in Gmail with a screenshot (Gmail-
prabhutiwari111@gmail.com)

**Comment by quantosapplications** [comment]
Me too I'm experiencing this issue.

When I run flutter build apk 

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processReleaseResources'.               
> Android resource linking failed                                       
  /Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-mobile/build/app/intermediates/merged_manifests/release/AndroidManifest.xml:106: AAPT: error: resource xml/provider_paths (aka com.bigartwall.mobile:xml/provider_paths) not found.
                                                                        
  error: failed processing manifest.                                    
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 53s
```

If I remove from AndroidManifest.xml

```
<provider android:name="androidx.core.content.FileProvider"
            android:authorities="com.bigartwall.mobile.social.share.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
```

it compile but I can't share to feed instagram

**Comment by quantosapplications** [comment]
**Solved for me**

I had to add a file in `/android/app/src/main/res/xml/provider_paths.xml` with this content:

```
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <files-path name="files" path="/"/>
    <external-files-path name="ext_files" path="/" />
    <cache-path name="cache_files" path="/" />
</paths>
```
You can refer to https://developer.android.com/reference/androidx/core/content/FileProvider for correctly setup this file.

Now it works, it compile and also share correctly on instagram.

**Comment by srinivasii** [comment]
But I am getting the below exception. can some one help me on this

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDevelopmentDebugResources'.
> Android resource linking failed
  C:\Users\user\.gradle\caches\transforms-1\files-1.1\jetified-facebook-login-4.39.0.aar\198b7531fabed44cd94796ccbbb94713\res\drawable\com_facebook_button_login_background.xml:26: AAPT: error: resource color/com_facebook_button_background_color_focused_disabled (aka com.sago.dev:color/com_facebook_button_background_color_focused_disabled) not found.

  C:\Users\user\.gradle\caches\transforms-1\files-1.1\jetified-facebook-login-4.39.0.aar\198b7531fabed44cd94796ccbbb94713\res\drawable\com_facebook_button_login_background.xml:38: AAPT: error: resource color/com_facebook_button_background_color_focused (aka com.sago.dev:color/com_facebook_button_background_color_focused) not found.

  C:\Users\user\.gradle\caches\transforms-1\files-1.1\jetified-facebook-login-4.39.0.aar\198b7531fabed44cd94796ccbbb94713\res\drawable\com_facebook_button_login_background.xml:39: AAPT: error: resource color/com_facebook_button_border_color_focused (aka com.sago.dev:color/com_facebook_button_border_color_focused) not found.

  error: failed linking file resources.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`
