### ISSUE TITLE
Example app contains more functionality than published plugin

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [romatroskin/social_share_plugin#2]
Hello,
The published plugin only has 2 methods: shareToFeedInstagram, shareToFeedFacebook
The example has more methods: shareToFeedInstagram, shareToFeedFacebook, shareToFeedFacebookLink, shareToTwitter.
When I am integrating the published plugin, I cannot use the other 2 methods.
How do I add the plugin to my existing project?
Thank you.

**Comment by vynerth0214** [comment]
I agree with this.

This commit has not been published or included in 0.2.0 version: 
> provider instagram share version

Would you be so kind as to publish the latest commits? Thank you so much!

**Comment by romatroskin** [comment]
yep, I have to push the latest version to the repo

**Comment by rakeshkhoodeeram** [comment]
or you can point your pubspec to the git url or a fork of the project
example in pubspec put the below: 
social_share_plugin:
    git:
      url: https://github.com/romatroskin/social_share_plugin.git
      ref: master

**Comment by quantosapplications** [comment]
Hello @romatroskin I found this plugin very useful, thank you!
Is this version going to be published on pub?
Also, the version on GitHub is using facebook v 4.41.0 instead flutter_facebook_login use 4.39.0.
Is this necessary for the correct working of the plugin, or can be downgraded?
Thank you!

**Comment by romatroskin** [comment]
already published updated version
