### ISSUE TITLE
Instagram share doesnt pop up.

### ISSUE THREAD

**Issue by Linspirit98** [romatroskin/social_share_plugin#32]
After picking an image from the library, the Instagram app doesn't pop up. Any help?
![IMG_CA654C1D3117-1](https://user-images.githubusercontent.com/51519489/81759890-f3d2c000-9493-11ea-9124-4798ea7a3ff9.jpeg)

Thank you in advance!

**Comment by Alezhka** [comment]
I have the same problem (iPhone 7).

**Comment by zenkog** [comment]
+1 I also have the same problem. When can we get some update on this issue?

**Comment by gunantosteven** [comment]
Still no update ? Let's find out why

**Comment by lizhuoyuan** [comment]
> Still no update ? Let's find out why

Have you found the reason？

**Comment by dhanrajVerma** [comment]
I too have the same problem

**Comment by gunantosteven** [comment]
Try using [this](https://github.com/gunantosteven/social_share_plugin), but it's not perfect

**Comment by romatroskin** [comment]
Fixed with #49 and #49 in 737139821d3efe3a8bce60424e5d3110550947d9
