### ISSUE TITLE
2 things that annoyed me abou this plugin ‼️

### ISSUE THREAD

**Issue by MikeMannox** [romatroskin/social_share_plugin#35]
1. on the the pub.dev page for [https://pub.dev/packages/social_share_plugin](https://pub.dev/packages/social_share_plugin) for the homepage link you link to [https://romatroskin.github.io/](https://romatroskin.github.io/) - This is not what is expected.
When I click that link I had to find a link to the this github repo and then search through a bunch of forked repos to find this. Please be a nice citizen and fix that would you?
2. Your documentation is better than some others, which is a start, but if (say) Facebook is not installed why do you take the user to the app/play store? The user doesn't have FB installed because they don't want it on their device. **Open the Dialog to show the web share option.**

**Comment by hermitdave** [comment]
Agreed about not taking user to store. It should use webview

**Comment by MikeMannox** [comment]
Not bothering with this library. Please remove it from Pub.Dev

**Comment by romatroskin** [comment]
1. Maybe you can open your eyes and see the REPOSITORY link on the pub?
Please remove yourself from GitHub.
