### ISSUE TITLE
share To Feed Instagram is not working

### ISSUE THREAD

**Issue by singlakaran** [romatroskin/social_share_plugin#4]
i get this error agin and again
file:///storage/emulated/0/DCIM/Camera/159.jpg exposed beyond app through ClipData.Item.getUri()

here is my code 
`File file = File('/storage/emulated/0/DCIM/Camera/159.jpg');
await SocialSharePlugin.shareToFeedInstagram('image/*', file.path);`

but facebook is working fine for me

**Comment by singlakaran** [comment]
i got solution 
i made Pull request please review and merge
https://github.com/romatroskin/social_share_plugin/pull/5

**Comment by romatroskin** [comment]
your way is dirty hack, already fixed in the master by the way, just not published to the pub

**Comment by singlakaran** [comment]
then please tell me right way to solve this problem.

**Comment by romatroskin** [comment]
already published updated version to the pub
