### ISSUE TITLE
Cannot Share via Facebook Api Error.

### ISSUE THREAD

**Issue by sagar2411** [romatroskin/social_share_plugin#43]
I was currently working on the application to share via facebook and it was going fine but in 2 days its giving error for the facebook share and it says API error has any one noticed kind of issue. Please let me know.

**Comment by andrea689** [comment]
I noticed that with my facebook account is working (facebook developer account), but with other accounts no. I tried to switch facebook app from "in development" to "live", but the error persist.

@sagar2411 do you have solved this?

**Comment by BhavyKoshti9spl** [comment]
any updates on this one? i am not able to share via facebook. @andrea689 @sagar2411

**Comment by andrea689** [comment]
try to switch your facebook app to "Live", I solved after few time I switched

**Comment by BhavyKoshti9spl** [comment]
> try to switch your facebook app to "Live", I solved after few time I switched

Thanks buddy it worked but takes some time from facebook to confirm it.
