### ISSUE TITLE
share instagram feed on ios doesn't work

### ISSUE THREAD

**Issue by 45minuto** [romatroskin/social_share_plugin#48]
When i try to share a link on instagram feed, it doesn't work because it tried to share a file ".igo", but this kind of implementation on ios doesn't work anymore.

I've forked this repo and changed the ios implementation, and i did a pull request. If you want, you can merge it

PS: I left some comments in the ios implementation in order to be easily understandable

#47

**Comment by romatroskin** [comment]
Fixed.
