### ISSUE TITLE
ios Share not working (Solution)

### ISSUE THREAD

**Issue by parthvirani95** [romatroskin/social_share_plugin#49]
**This is not my issue but I attached a solution for @45minuto just because I can't reply to their quotations sorry for this** 
Please refer to this StackOverflow solution [https://stackoverflow.com/questions/26833348/uidocumentinteractioncontroller-share-via-instagram-and-only-instagram](URL) this issue is because of iOS 13 only support .ig Extention file based on this plugin sharing functions so for that, we need to change below i attached image <img width="1128" alt="Screenshot 2021-02-22 at 1 56 31 PM 1" src="https://user-images.githubusercontent.com/49033709/108682336-2d9e2000-7516-11eb-8d07-164f227c0fd8.png">
so **for changing this open xcode and find "instagramShare"** and on that function change to like `- (void)instagramShare:(NSString*)imagePath {
    NSError *error = nil;
    UIViewController* controller = [UIApplication sharedApplication].delegate.window.rootViewController;
//    [[NSFileManager defaultManager] moveItemAtPath:imagePath toPath:[NSString stringWithFormat:@"%@.igo", imagePath] error:&error];
    NSURL *path;
    if (@available(iOS 13.0, *)) {
        [[NSFileManager defaultManager] moveItemAtPath:imagePath toPath:[NSString stringWithFormat:@"%@.ig", imagePath] error:&error];
        path = [NSURL URLWithString:[NSString stringWithFormat:@"file://%@.ig", imagePath]];
    } else {
     [[NSFileManager defaultManager] moveItemAtPath:imagePath toPath:[NSString stringWithFormat:@"%@.igo", imagePath] error:&error];
        path = [NSURL URLWithString:[NSString stringWithFormat:@"file://%@.igo", imagePath]];
    }
    _dic = [UIDocumentInteractionController interactionControllerWithURL:path];
    _dic.UTI = @"com.instagram.exclusivegram";
    if (![_dic presentOpenInMenuFromRect:CGRectZero inView:controller.view animated:TRUE]) {
        NSLog(@"Error sharing to instagram");
    };
}`
<img width="1038" alt="Screenshot 2021-02-22 at 2 02 19 PM 1" src="https://user-images.githubusercontent.com/49033709/108682702-a69d7780-7516-11eb-87a8-b754d0bf4014.png">
**this solve my issue so i hope this will help and sorry for my english**

**Comment by romatroskin** [comment]
Fixed.
