### ISSUE TITLE
[Android] android 10 or hight version device, can't open facebook share dialog

### ISSUE THREAD

**Issue by hzqhzqhzq** [romatroskin/social_share_plugin#57]
android 8 and low version , the facebook share dialog is normal, when i use android 10 device to test, that can't open share dialog

my AndroidManifest.xml

       <queries>
          <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
       </queries>

       <meta-data android:name="com.facebook.sdk.ApplicationId"
           android:value="@string/facebook_app_id"/>

       <meta-data android:name="com.facebook.sdk.ApplicationName"
           android:value="@string/app_name"/>

       <activity android:name="com.facebook.FacebookActivity"
           android:configChanges=
               "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
           android:label="@string/app_name" />

       <provider android:authorities="com.facebook.app.FacebookContentProvider00000000000"
           android:name="com.facebook.FacebookContentProvider"
           android:exported="true"/>

flutter  code

`await SocialSharePlugin.shareToFeedFacebookLink(quote: share.shareDescription, url: share.shareUrl);`

any problem?

**Comment by romatroskin** [comment]
FacebookContentProvider00000000000 instead of 00...0 should be your app id !

https://github.com/romatroskin/social_share_plugin/issues/53#issuecomment-1261118930
