### ISSUE TITLE
New Facebook rule for sharing to Instagram Stories

### ISSUE THREAD

**Issue by aytunch** [romatroskin/social_share_plugin#58]
Starting from November Instagram story share won't be possible if i understand correctly. (Unless their new api rules are met)
https://developers.facebook.com/docs/instagram/sharing-to-stories
https://developers.facebook.com/blog/post/2022/10/10/introducing-important-update-to-Instagram-sharing-to-stories/
Would this change effect this plugin?

**Comment by romatroskin** [comment]
Hello! No, this new rules will not affect latest implementation, thanks!
